[package]
name = "attribute-pseudoblock"
description = "Apply an attribute to a section of code that can't be put in a block"
version = "0.1.0"
authors = ["RosieTheGhostie"]
edition = "2021"

[lib]
crate-type = ["lib"]
path = "src/lib.rs"
